spring:
  application:
    name: auth-service
  threads:
    virtual:
      enabled: true
  config:
    import: "optional:configserver:${CONFIG_SERVER_URI:http://config-service:8888}"

server:
  port: 8100